rails/config/routes.rb
Rails.application.routes.draw do
  resources :todos

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails/app/models/todo.rb
class Todo < ApplicationRecord
end

rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

rails/app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end

  def new
  end

  def create
    @todo = Todo.new create_params
    @todo.save!
  end

  def show
    @todo = Todo.find find_params
  end

  def edit
    @todo = Todo.find find_params
  end

  def update
    @todo = Todo.find find_params
    @todo.update!(update_params)
  end

  def destroy
    @todo = Todo.find find_params
  end

  private

  def create_params
    params.require(:todo).permit(:name, :date, :description)
  end

  def find_params
    params.require(:id)
  end

  def update_params
    params.permit(:name, :date, :description)
  end
end

rails/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/app/helpers/todos_helper.rb
module TodosHelper
end

rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Test1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

rails/app/views/todos/create.html.haml
%h1 Your new task is
%p Name:
= @todo.name
; Description:
= @todo.description
; Until:
= @todo.date

rails/app/views/todos/destroy.html.haml
%h1 Todos#destroy
%p Find me in app/views/todos/destroy.html.haml

rails/app/views/todos/edit.html.haml
%h1 Todos#edit
%p Find me in app/views/todos/edit.html.haml

rails/app/views/todos/index.html.haml
%h1 Todos List
%p What do I have to do?

.container
  - if @todos.length > 0
    %table
      %thead
        %tr
          %td Name
          %td Date
          %td Description
      %tbody
        - @todos.each do |todo|
          %tr
            %td= todo.name
            %td= todo.date
            %td= todo.description

rails/app/views/todos/new.html.haml
%h1 Create a new task

.container
  = form_for :todo, url: todos_path do |f|
    %label
      Name
      = f.text_field :name

    %label
      Date
      = f.date_field :date

    %label
      Description
      = f.text_area :description

    = f.submit

rails/app/views/todos/show.html.haml
%h1 Todos#show
%p Find me in app/views/todos/show.html.haml

rails/app/views/todos/update.html.haml
%h1 Todos#update
%p Find me in app/views/todos/update.html.haml